In [1]:
import pandas as al
import numpy as su
import seaborn as ala


## Loading dataset

In [2]:
sur=al.read_csv('penguins.csv')
sur.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
3  Adelie  Torgersen             NaN            NaN                NaN   
4  Adelie  Torgersen            36.7           19.3              193.0   

   body_mass_g     sex  
0       3750.0    MALE  
1       3800.0  FEMALE  
2       3250.0  FEMALE  
3          NaN     NaN  
4       3450.0  FEMALE

In [3]:
sur.shape


(344, 7)

In [4]:
sur.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   species            344 non-null    object 
 1   island             344 non-null    object 
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object 
dtypes: float64(4), object(3)
memory usage: 18.9+ KB


In [5]:
sur.isnull().sum()

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64

## drop the null

In [6]:
sur.dropna(inplace=True)

In [7]:
sur.isnull().sum()

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
dtype: int64

In [8]:
sur.sex.unique()

array(['MALE', 'FEMALE'], dtype=object)

In [9]:
al.get_dummies(sur['sex']).head()

FEMALE  MALE
0       0     1
1       1     0
2       1     0
4       1     0
5       0     1

In [10]:
sex=al.get_dummies(sur['sex'],drop_first=True)
sex.head()

MALE
0     1
1     0
2     0
4     0
5     1

In [11]:
sur.island.unique()

array(['Torgersen', 'Biscoe', 'Dream'], dtype=object)

In [12]:
al.get_dummies(sur['island']).head()

Biscoe  Dream  Torgersen
0       0      0          1
1       0      0          1
2       0      0          1
4       0      0          1
5       0      0          1

In [13]:
island=al.get_dummies(sur['island'],drop_first=True)
island.head()

Dream  Torgersen
0      0          1
1      0          1
2      0          1
4      0          1
5      0          1

In [14]:
da=al.concat([sur,sex,island],axis=1)
da.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
4  Adelie  Torgersen            36.7           19.3              193.0   
5  Adelie  Torgersen            39.3           20.6              190.0   

   body_mass_g     sex  MALE  Dream  Torgersen  
0       3750.0    MALE     1      0          1  
1       3800.0  FEMALE     0      0          1  
2       3250.0  FEMALE     0      0          1  
4       3450.0  FEMALE     0      0          1  
5       3650.0    MALE     1      0          1

In [15]:
da.drop(["island","sex",],axis=1,inplace=True)
da.head()

species  bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  \
0  Adelie            39.1           18.7              181.0       3750.0   
1  Adelie            39.5           17.4              186.0       3800.0   
2  Adelie            40.3           18.0              195.0       3250.0   
4  Adelie            36.7           19.3              193.0       3450.0   
5  Adelie            39.3           20.6              190.0       3650.0   

   MALE  Dream  Torgersen  
0     1      0          1  
1     0      0          1  
2     0      0          1  
4     0      0          1  
5     1      0          1

## Creating separate target variable

In [16]:
Y=da.species
Y.head()

0    Adelie
1    Adelie
2    Adelie
4    Adelie
5    Adelie
Name: species, dtype: object

In [17]:
Y.unique()

array(['Adelie', 'Chinstrap', 'Gentoo'], dtype=object)

In [18]:
Y=Y.map({'Adelie':0,'Chinstrap':1,'Gentoo':2})
Y.head()

0    0
1    0
2    0
4    0
5    0
Name: species, dtype: int64

In [19]:
da.head()

species  bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  \
0  Adelie            39.1           18.7              181.0       3750.0   
1  Adelie            39.5           17.4              186.0       3800.0   
2  Adelie            40.3           18.0              195.0       3250.0   
4  Adelie            36.7           19.3              193.0       3450.0   
5  Adelie            39.3           20.6              190.0       3650.0   

   MALE  Dream  Torgersen  
0     1      0          1  
1     0      0          1  
2     0      0          1  
4     0      0          1  
5     1      0          1

## Dropping the traget variable

In [20]:
da.drop(["species"],axis=1,inplace=True)
da.head()

bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  MALE  Dream  \
0            39.1           18.7              181.0       3750.0     1      0   
1            39.5           17.4              186.0       3800.0     0      0   
2            40.3           18.0              195.0       3250.0     0      0   
4            36.7           19.3              193.0       3450.0     0      0   
5            39.3           20.6              190.0       3650.0     1      0   

   Torgersen  
0          1  
1          1  
2          1  
4          1  
5          1

In [21]:
X=da

## Splitting the data into training and test data

In [22]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.3,random_state=0)


In [23]:
print('x_train',x_train.shape)
print('x_test',x_test.shape)
print('y_train',y_train.shape)
print('y_test',y_test.shape)

x_train (233, 7)
x_test (100, 7)
y_train (233,)
y_test (100,)


## Training random forest classification on trainning set

In [24]:
from sklearn.ensemble import RandomForestClassifier
Classifier=RandomForestClassifier(n_estimators=5,criterion='entropy',random_state=0)
Classifier.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=5, random_state=0)

## Predicting the test results

In [25]:
y_pre=Classifier.predict(x_test)
y_pre

array([0, 0, 2, 0, 0, 0, 1, 2, 2, 1, 2, 0, 0, 1, 0, 0, 2, 0, 1, 0, 0, 0,
       2, 2, 2, 2, 0, 0, 0, 0, 0, 1, 0, 1, 0, 2, 1, 0, 1, 0, 2, 2, 0, 0,
       0, 0, 0, 0, 2, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 2, 0, 1, 0, 2, 0, 0,
       2, 2, 1, 2, 2, 1, 2, 1, 0, 2, 0, 2, 0, 2, 1, 0, 2, 2, 1, 2, 1, 0,
       0, 2, 2, 0, 2, 0, 2, 0, 2, 0, 2, 2], dtype=int64)

## confusion matrix

In [26]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report,accuracy_score

In [27]:
confusion_matrix(y_test,y_pre)


array([[48,  0,  0],
       [ 1, 15,  0],
       [ 1,  0, 35]], dtype=int64)

In [28]:
accuracy_score(y_test, y_pre)

0.98

In [33]:
from sklearn.ensemble import RandomForestClassifier
Classifier=RandomForestClassifier(n_estimators=7,criterion='gini',random_state=0)
Classifier.fit(x_train,y_train)

RandomForestClassifier(n_estimators=7, random_state=0)

In [30]:
y_pre=Classifier.predict(x_test)
y_pre

array([0, 0, 2, 0, 0, 0, 1, 2, 2, 1, 2, 0, 0, 1, 0, 0, 2, 0, 1, 0, 0, 0,
       2, 2, 2, 2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 2, 1, 0, 1, 0, 2, 2, 0, 0,
       0, 0, 0, 0, 2, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 2, 0, 1, 0, 2, 0, 0,
       2, 2, 1, 2, 2, 1, 2, 1, 0, 2, 0, 2, 0, 2, 1, 2, 2, 2, 1, 2, 1, 0,
       0, 2, 2, 0, 2, 0, 2, 0, 2, 0, 2, 2], dtype=int64)

In [31]:
accuracy_score(y_test, y_pre)

0.98